yepes/contrib/thumbnails/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import url

from yepes.apps import apps

ConfigurationsTestView = apps.get_class('thumbnails.views', 'ConfigurationsTestView')
OptionsTestView = apps.get_class('thumbnails.views', 'OptionsTestView')


urlpatterns = [
    url(r'^configurations/$',
        ConfigurationsTestView.as_view(),
        name='thumbnail_configurations',
    ),
    url(r'^options/$',
        OptionsTestView.as_view(),
        name='thumbnail_options',
    ),
]

yepes/contrib/thumbnails/models.py
# -*- coding:utf-8 -*-

from yepes.apps import apps

AbstractConfiguration = apps.get_class('thumbnails.abstract_models', 'AbstractConfiguration')
AbstractSource = apps.get_class('thumbnails.abstract_models', 'AbstractSource')
AbstractThumbnail = apps.get_class('thumbnails.abstract_models', 'AbstractThumbnail')


class Configuration(AbstractConfiguration):
    pass

class Source(AbstractSource):
    pass

class Thumbnail(AbstractThumbnail):
    pass

yepes/contrib/thumbnails/views.py
# -*- coding:utf-8 -*-

from __future__ import unicode_literals

from django.core.files.storage import FileSystemStorage
from django.views.generic import TemplateView

from yepes.apps import apps
from yepes.views import ListView

Configuration = apps.get_model('thumbnails', 'Configuration')
SourceFile = apps.get_class('thumbnails.files', 'SourceFile')


class TestMixin(object):

    def get_context_data(self, **kwargs):
        context = super(TestMixin, self).get_context_data(**kwargs)
        context['source'] = self.get_source_file()
        return context

    def get_source_file(self):
        app_config = apps.get_app_config('thumbnails')
        app_static_dir = os.path.join(app_config.path, 'static')
        app_storage = FileSystemStorage(app_static_dir)
        media_storage = FileSystemStorage()
        path = 'thumbnails/wolf.jpg'
        if not media_storage.exists(path):
            media_storage.save(path, app_storage.open(path))
        elif app_storage.modified_time(path) > media_storage.modified_time(path):
            media_storage.delete(path)
            media_storage.save(path, app_storage.open(path))

        return SourceFile(media_storage.open(path), path, media_storage)


class ConfigurationsTestView(TestMixin, ListView):

    model = Configuration
    template_name = 'thumbnails/configurations.html'


class OptionsTestView(TestMixin, TemplateView):

    template_name = 'thumbnails/options.html'

yepes/contrib/thumbnails/templates/thumbnails/configurations.html
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <title>Thumbnail Configurations</title>
  <style>
    .thumbnail {
      line-height: 0;
    }
    .thumbnail:hover {
      background: #FF0000;
    }
  </style>
</head>
<body>
  <h1>Thumbnail Configurations</h1>
  <h2>Source</h2>
  <p>{{ source.name }}</p>
  <p><img src="{{ source.url }}" width="{{ source.width }}" height="{{ source.height }}"></p>
{% load thumbnails %}
{% for config in configuration_list %}
  {% get_thumbnail source config force_generation=True %}
  <h2>Thumbnail: {{ config.key }}</h2>
  <p>{{ thumbnail.name }}</p>
  <p class="thumbnail" style="height:{{ config.height }}px; width:{{ config.width }}px">
    <img src="{{ thumbnail.url }}" width="{{ thumbnail.width }}" height="{{ thumbnail.height }}">
  </p>
{% endfor %}
</body>
</html>

yepes/contrib/thumbnails/templates/thumbnails/options.html
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <title>Thumbnail Options</title>
  <style>
    .thumbnail {
      line-height: 0;
    }
    .thumbnail:hover {
      background: #FF0000;
    }
  </style>
</head>
<body>
  <h1>Thumbnail Options</h1>
  <h2>Source</h2>
  <p>{{ source.name }}</p>
  <p><img src="{{ source.url }}" width="{{ source.width }}" height="{{ source.height }}"></p>
{% load thumbnails %}
  {% make_configuration 200 200 %}
  {% get_thumbnail source configuration force_generation=True %}
  <h2>Thumbnail: w200_h200</h2>
  <p>{{ thumbnail.name }}</p>
  <p class="thumbnail" style="height:200px; width:200px">
    <img src="{{ thumbnail.url }}" width="{{ thumbnail.width }}" height="{{ thumbnail.height }}">
  </p>
  {% make_configuration 200 200 mode='scale' %}
  {% get_thumbnail source configuration force_generation=True %}
  <h2>Thumbnail: w200_h200_mSCALE</h2>
  <p>{{ thumbnail.name }}</p>
  <p class="thumbnail" style="height:200px; width:200px">
    <img src="{{ thumbnail.url }}" width="{{ thumbnail.width }}" height="{{ thumbnail.height }}">
  </p>
  {% make_configuration 200 200 mode='fit' %}
  {% get_thumbnail source configuration force_generation=True %}
  <h2>Thumbnail: w200_h200_mFIT</h2>
  <p>{{ thumbnail.name }}</p>
  <p class="thumbnail" style="height:200px; width:200px">
    <img src="{{ thumbnail.url }}" width="{{ thumbnail.width }}" height="{{ thumbnail.height }}">
  </p>
  {% make_configuration 200 200 mode='fill' %}
  {% get_thumbnail source configuration force_generation=True %}
  <h2>Thumbnail: w200_h200_mFILL</h2>
  <p>{{ thumbnail.name }}</p>
  <p class="thumbnail" style="height:200px; width:200px">
    <img src="{{ thumbnail.url }}" width="{{ thumbnail.width }}" height="{{ thumbnail.height }}">
  </p>
  {% make_configuration 200 200 mode='pad' %}
  {% get_thumbnail source configuration force_generation=True %}
  <h2>Thumbnail: w200_h200_mPAD</h2>
  <p>{{ thumbnail.name }}</p>
  <p class="thumbnail" style="height:200px; width:200px">
    <img src="{{ thumbnail.url }}" width="{{ thumbnail.width }}" height="{{ thumbnail.height }}">
  </p>
  {% make_configuration 200 200 '00ff00' mode='pad' gravity='north_west' %}
  {% get_thumbnail source configuration force_generation=True %}
  <h2>Thumbnail: w200_h200_b00FF00_mPAD_gNORTHWEST</h2>
  <p>{{ thumbnail.name }}</p>
  <p class="thumbnail" style="height:200px; width:200px">
    <img src="{{ thumbnail.url }}" width="{{ thumbnail.width }}" height="{{ thumbnail.height }}">
  </p>
  {% make_configuration 200 200 mode='pad' gravity='south_east' format='png' %}
  {% get_thumbnail source configuration force_generation=True %}
  <h2>Thumbnail: w200_h200_mPAD_gSOUTHEAST_fPNG64</h2>
  <p>{{ thumbnail.name }}</p>
  <p class="thumbnail" style="height:200px; width:200px">
    <img src="{{ thumbnail.url }}" width="{{ thumbnail.width }}" height="{{ thumbnail.height }}">
  </p>
  {% make_configuration 200 200 mode='crop' %}
  {% get_thumbnail source configuration force_generation=True %}
  <h2>Thumbnail: w200_h200_mCROP</h2>
  <p>{{ thumbnail.name }}</p>
  <p class="thumbnail" style="height:200px; width:200px">
    <img src="{{ thumbnail.url }}" width="{{ thumbnail.width }}" height="{{ thumbnail.height }}">
  </p>
  {% make_configuration 200 200 mode='scale' algorithm='liquid' %}
  {% get_thumbnail source configuration force_generation=True %}
  <h2>Thumbnail: w200_h200_mSCALE_aLIQUID</h2>
  <p>{{ thumbnail.name }}</p>
  <p class="thumbnail" style="height:200px; width:200px">
    <img src="{{ thumbnail.url }}" width="{{ thumbnail.width }}" height="{{ thumbnail.height }}">
  </p>
</body>
</html>